//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inf
    {
        public int Id { get; set; }
        public string About { get; set; }
        public string Preview { get; set; }
    }
}
